### ISSUE TITLE
Lib on PyPI

### ISSUE THREAD

**Issue by WorkHardes** [rickmark/python-libimobiledevice#3]
I input pip install libmpbiledevice.
But https://pypi.org/project/libimobiledevice/ - this is an old version of your library. It uses ctypes and cdll. And it has version 0.4.
I saw the code of this library, but it is not this repository.
Please update your code in PYPI and and give feedback!

**Comment by rickmark** [comment]
The code exists on an old employer laptop - I'm in the process of moving / re-creating the Cython bindings there in PyPI so we should see fixes here soon

**Comment by rickmark** [comment]
Sorry - NVM - Got the current code converged - note that the code is moved under a package of "late" as there will be early bindings as well
